/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElText: typeof import('element-plus/es')['ElText']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IEpClose: typeof import('~icons/ep/close')['default']
    IEpDelete: typeof import('~icons/ep/delete')['default']
    IEpDocument: typeof import('~icons/ep/document')['default']
    IEpDocumentCopy: typeof import('~icons/ep/document-copy')['default']
    IEpFullScreen: typeof import('~icons/ep/full-screen')['default']
    IEpInfoFilled: typeof import('~icons/ep/info-filled')['default']
    IEpKey: typeof import('~icons/ep/key')['default']
    IEpLink: typeof import('~icons/ep/link')['default']
    IEpLoading: typeof import('~icons/ep/loading')['default']
    IEpMenu: typeof import('~icons/ep/menu')['default']
    IEpMinus: typeof import('~icons/ep/minus')['default']
    IEpMoon: typeof import('~icons/ep/moon')['default']
    IEpPlus: typeof import('~icons/ep/plus')['default']
    IEpSearch: typeof import('~icons/ep/search')['default']
    IEpSetting: typeof import('~icons/ep/setting')['default']
    IEpStar: typeof import('~icons/ep/star')['default']
    IEpSunny: typeof import('~icons/ep/sunny')['default']
    IEpTickets: typeof import('~icons/ep/tickets')['default']
    IEpWarning: typeof import('~icons/ep/warning')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UpdateDialog: typeof import('./src/components/UpdateDialog.vue')['default']
  }
}
